services:
  postgres:
    image: postgres:16-alpine        # alpine, imagem menor
    container_name: exodeploy-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: exodeploy
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # vem do .env
      POSTGRES_DB: exodeploy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistencia

  redis:
      image: redis:7-alpine
      container_name: exodeploy-redis
      restart: unless-stopped
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
volumes:
  postgres_data:
  redis_data: