package provisioner

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"text/template"
	"time"
)

const (
	SitesAvailableDir = "/etc/nginx/sites-available"
	SitesEnabledDir   = "/etc/nginx/sites-enabled"
	CertbotEmail      = "admin@%s"
)

// NginxConfig contém os dados para gerar o vhost
type NginxConfig struct {
	AppName       string
	Domain        string
	ContainerPort int
	EnableSSL     bool // ignorado em TunnelMode
	TunnelMode    bool
}

// NginxProvisioner gera configs e opcionalmente configura Certbot/SSL
type NginxProvisioner struct {
	email string
}

func NewNginxProvisioner(email string) *NginxProvisioner {
	return &NginxProvisioner{email: email}
}

var nginxConfTemplate = template.Must(template.New("vhost").Parse(`# Auto-generated by ExoDeploy Agent — {{.AppName}}
# DO NOT EDIT MANUALLY
{{if .TunnelMode}}
# Cloudflare Tunnel mode: Nginx só escuta no loopback, TLS gerenciado pelo Cloudflare Edge
{{end}}
server {
    listen 127.0.0.1:80;
    server_name {{.Domain}};
{{if .TunnelMode}}

    # Cloudflare verifica (garante que o tráfego veio do tunnel)
    set_real_ip_from 127.0.0.1;
    real_ip_header    CF-Connecting-IP;
{{end}}
    location / {
        proxy_pass http://127.0.0.1:{{.ContainerPort}};
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Port   $server_port;
{{if .TunnelMode}}
        proxy_set_header CF-Connecting-IP   $http_cf_connecting_ip;
        proxy_set_header CF-IPCountry       $http_cf_ipcountry;
        proxy_set_header CF-Ray             $http_cf_ray;
        proxy_set_header CF-Visitor         $http_cf_visitor;
{{end}}
    }
}
`))

// Provision gera o vhost do Nginx, habilita e (opcionalmente) roda o Certbot
func (p *NginxProvisioner) Provision(cfg NginxConfig) error {
	log.Printf("🌐 Provisionando Nginx para %s (%s)", cfg.AppName, cfg.Domain)

	// 1. Gera o arquivo de configuração
	configPath := p.configPath(cfg.AppName)
	if err := p.writeConfig(configPath, cfg); err != nil {
		return fmt.Errorf("erro ao escrever config nginx: %w", err)
	}

	// 2. Cria symlink em sites-enabled
	if err := p.enableSite(cfg.AppName); err != nil {
		return fmt.Errorf("erro ao habilitar site: %w", err)
	}

	// 3. Testa a configuração
	if err := p.testConfig(); err != nil {
		p.disableSite(cfg.AppName) // rollback
		return fmt.Errorf("nginx config test falhou: %w", err)
	}

	// 4. Reload do nginx
	if err := p.reloadNginx(); err != nil {
		p.disableSite(cfg.AppName) // rollback
		return fmt.Errorf("nginx reload falhou: %w", err)
	}

	// 5. Se SSL, roda o Certbot
	if cfg.EnableSSL && !cfg.TunnelMode {
		log.Printf("🔒 Solicitando certificado SSL para %s (modo standalone)", cfg.Domain)
		if err := p.runCertbot(cfg); err != nil {
			log.Printf("⚠️  Certbot falhou, mas o site HTTP continua ativo: %v", err)
		} else {
			p.reloadNginx()
		}
	} else if cfg.TunnelMode {
		log.Printf("☁️  TunnelMode ativo—TLS gerenciado pelo Cloudflare Edge, Nginx bind no 127.0.0.1:80")
	}

	log.Printf("✅ Nginx configurado para %s", cfg.Domain)
	return nil
}

// Remove limpa o vhost e reload
func (p *NginxProvisioner) Remove(appName string) {
	p.disableSite(appName)
	_ = os.Remove(p.configPath(appName))
	p.reloadNginx()
	log.Printf("🗑️  Nginx vhost removido para %s", appName)
}

// --- internals ---

func (p *NginxProvisioner) configPath(appName string) string {
	return fmt.Sprintf("%s/%s.conf", SitesAvailableDir, appName)
}

func (p *NginxProvisioner) writeConfig(path string, cfg NginxConfig) error {
	var buf bytes.Buffer
	if err := nginxConfTemplate.Execute(&buf, cfg); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0644)
}

func (p *NginxProvisioner) enabledLink(appName string) string {
	return fmt.Sprintf("%s/%s.conf", SitesEnabledDir, appName)
}

func (p *NginxProvisioner) enableSite(appName string) error {
	// Cria diretórios se não existirem
	for _, dir := range []string{SitesAvailableDir, SitesEnabledDir} {
		os.MkdirAll(dir, 0755)
	}

	siteCfg := p.configPath(appName)
	linkPath := p.enabledLink(appName)

	// Remove symlink antigo se existir
	os.Remove(linkPath)

	return os.Symlink(siteCfg, linkPath)
}

func (p *NginxProvisioner) disableSite(appName string) {
	os.Remove(p.enabledLink(appName))
}

func (p *NginxProvisioner) testConfig() error {
	cmd := exec.Command("nginx", "-t")
	out, err := cmd.CombinedOutput()
	log.Printf("🔍 nginx -t: %s", string(out))
	return err
}

func (p *NginxProvisioner) reloadNginx() error {
	cmd := exec.Command("nginx", "-s", "reload")
	return cmd.Run()
}

func (p *NginxProvisioner) runCertbot(cfg NginxConfig) error {
	email := p.email
	if email == "" {
		email = fmt.Sprintf(CertbotEmail, cfg.Domain)
	}

	// Garante pasta do webroot
	webroot := fmt.Sprintf("/var/www/certbot/%s", cfg.AppName)
	os.MkdirAll(webroot, 0755)

	args := []string{
		"certonly",
		"--nginx",
		"--non-interactive",
		"--agree-tos",
		"--email", email,
		"-d", cfg.Domain,
	}

	log.Printf("🔐 Executando: certbot %v", args)
	cmd := exec.Command("certbot", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	// Certbot pode demorar — timeout de 5 minutos
	cmd.WaitDelay = 5 * time.Minute
	return cmd.Run()
}
